# cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/adaptive-trading-platform', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/adaptive-trading-platform']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'adaptive-trading-platform',
    '--image', 'gcr.io/$PROJECT_ID/adaptive-trading-platform',
    '--region', 'us-central1',
    '--platform', 'managed',
    '--allow-unauthenticated'
  ]
